# TensorFlow Basics

In [274]:
#importing tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [275]:
#creating tensor using tf.constant as scalar
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [276]:
#ndim means number of dimensions
scalar.ndim

0

In [277]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [278]:
vector.ndim

1

In [279]:
matrix = tf.constant([[10,7],[6,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  3]])>

In [280]:
matrix.ndim

2

In [281]:
tensor = tf.constant([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
    
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [282]:
tensor.ndim

3

## using tf.Variable()

In [283]:
changing_variable = tf.Variable(7)
unchanging_variable = tf.constant(7)
changing_variable, unchanging_variable


(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>)

In [284]:
changing_variable.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [285]:
changing_variable.assign_add(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=7>

In [286]:
tf.random.set_seed(4)
random_tensor = tf.random.normal([3,2,3])
random_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[-0.07676513, -0.2082602 ,  1.9333363 ],
        [ 1.175166  ,  1.4444144 ,  1.3351023 ]],

       [[ 0.0987538 ,  0.47003892, -0.89593434],
        [ 0.8269468 , -0.3298544 , -1.6903992 ]],

       [[ 2.1704402 , -1.0355538 ,  1.1871556 ],
        [ 0.44113445, -0.7447429 ,  1.2710264 ]]], dtype=float32)>

In [287]:
ones = tf.ones([3,2,3])
ones

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [288]:
ones.ndim

3

In [289]:
zeros = tf.zeros([3,3,4])
zeros

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [290]:
zeros.ndim

3

### shuffle the order of elements in a tensor

In [291]:
#shuffle a tensor (valuable for when you want to shuffle the data so the inherent
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [292]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [293]:
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [294]:
not_shuffled.ndim

2

### Turn NumPy arrays into Tensors

In [295]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [296]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4))
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

In [248]:
B.ndim

3

In [297]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [298]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [308]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [313]:
#get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("total number of elements  in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
total number of elements  in our tensor:  120
