# TensorFlow Basics

In [14]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [9]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [17]:
scalar.ndim

0

In [19]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [20]:
vector.ndim

1

In [21]:
matrix = tf.constant([[10,7],[6,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  3]])>

In [22]:
matrix.ndim

2

In [24]:
tensor = tf.constant([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
    
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [25]:
tensor.ndim

3