# TensorFlow Basics

In [30]:
#importing tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [26]:
#creating tensor using tf.constant as scalar
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [27]:
#ndim means number of dimensions
scalar.ndim

0

In [29]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [20]:
vector.ndim

1

In [21]:
matrix = tf.constant([[10,7],[6,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  3]])>

In [22]:
matrix.ndim

2

In [24]:
tensor = tf.constant([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
    
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [25]:
tensor.ndim

3

## using tf.Variable()

In [38]:
changing_variable = tf.Variable(7)
unchanging_variable = tf.constant(7)
changing_variable, unchanging_variable


(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>)

In [39]:
changing_variable.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [40]:
changing_variable.assign_add(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=7>

In [42]:
unchanging_variable.assign(5)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [63]:
tf.random.set_seed(2)
random_tensor = tf.random.normal([3,4,5])
random_tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[ 4.3616885e-01, -1.9093795e+00,  1.3789066e+00, -1.0405852e+00,
         -9.5584162e-04],
        [ 1.6947803e-01,  9.1563100e-01,  5.5124867e-01, -1.3496986e-01,
         -6.2053423e-02],
        [-3.6240190e-01,  2.3602743e-02,  2.4705699e-01, -5.0046819e-01,
         -1.2991054e+00],
        [-4.4570196e-01,  4.6087113e-01,  8.0322498e-01,  5.2492535e-01,
          1.3032788e+00]],

       [[ 1.4531673e-01,  2.0262724e-01,  1.1651053e+00,  6.8329424e-01,
         -4.5403641e-01],
        [-3.5521424e-01, -4.3858859e-01, -1.0941397e-01, -7.0730346e-01,
         -5.0057858e-01],
        [-1.8905621e+00,  1.0930265e+00, -1.1361686e+00, -5.8947110e-01,
         -1.5072331e+00],
        [ 4.2659181e-01,  5.5581480e-01, -6.4384454e-01,  6.8071300e-01,
          5.6758478e-02]],

       [[-4.2920363e-01, -3.8657099e-02, -4.5252687e-01,  1.2627861e+00,
         -8.2549155e-01],
        [ 1.9785652e+00,  3.9286941e-01, -3.8193396e-0