# TensorFlow Basics

In [2]:
#importing tensorflow
import tensorflow as tf
print(tf.__version__)


2.15.0


In [3]:
#creating tensor using tf.constant as scalar
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#ndim means number of dimensions
scalar.ndim

0

In [5]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,7],[6,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  3]])>

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
    
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [10]:
tensor.ndim

3

## using tf.Variable()

In [11]:
changing_variable = tf.Variable(7)
unchanging_variable = tf.constant(7)
changing_variable, unchanging_variable


(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>)

In [12]:
changing_variable.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [13]:
changing_variable.assign_add(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=7>

In [14]:
tf.random.set_seed(4)
random_tensor = tf.random.normal([3,2,3])
random_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[-0.07676513, -0.2082602 ,  1.9333363 ],
        [ 1.175166  ,  1.4444144 ,  1.3351023 ]],

       [[ 0.0987538 ,  0.47003892, -0.89593434],
        [ 0.8269468 , -0.3298544 , -1.6903992 ]],

       [[ 2.1704402 , -1.0355538 ,  1.1871556 ],
        [ 0.44113445, -0.7447429 ,  1.2710264 ]]], dtype=float32)>

In [15]:
ones = tf.ones([3,2,3])
ones

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [16]:
ones.ndim

3

In [17]:
zeros = tf.zeros([3,3,4])
zeros

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [18]:
zeros.ndim

3

### shuffle the order of elements in a tensor

In [19]:
#shuffle a tensor (valuable for when you want to shuffle the data so the inherent
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [20]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [21]:
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [22]:
not_shuffled.ndim

2

### Turn NumPy arrays into Tensors

In [23]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4))
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

In [25]:
2*3*4

24

In [26]:
tf.size(B).numpy()

24

In [27]:
B.ndim

3

In [28]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [29]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
tf.size(rank_4_tensor).numpy()

120

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
#get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("total number of elements  in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
total number of elements  in our tensor:  120


## Indexing Tensors

* tensors can be indexed just like python lists.
* how to identify parts of a shape

In [33]:
rank_4_tensor[:2, :, :2, :2]

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor[:1, :, :1, :]

<tf.Tensor: shape=(1, 3, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
tf.size(rank_4_tensor[:1, :, :1, :]).numpy()

15

In [36]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [37]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [40]:
#create a rank to a tensor (2 dinensions)
rank_2_tensor = tf.constant([
    [10,7],
    [3,4]
])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [42]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

### Expanding dimensions of the tensor

In [56]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [46]:
rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([2, 2, 1]), 3)

In [61]:
tf.expand_dims(rank_2_tensor, axis=1).numpy(), tf.expand_dims(rank_2_tensor, axis=1).shape

(array([[[10,  7]],
 
        [[ 3,  4]]]),
 TensorShape([2, 1, 2]))

### Manipulating tensors
***Basic operations***
`+`,`-`,`*`,`/`

In [62]:
m_tensor = tf.constant([[12,13,14],
                        [4,5,6]])
m_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 13, 14],
       [ 4,  5,  6]])>

In [66]:
add_tensor = tf.math.add(m_tensor,10)
add_tensor.numpy(), m_tensor.numpy()

(array([[22, 23, 24],
        [14, 15, 16]]),
 array([[12, 13, 14],
        [ 4,  5,  6]]))

In [68]:
another_add_tensor = m_tensor + 10
another_add_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[22, 23, 24],
       [14, 15, 16]])>

In [69]:
sub_tensor = tf.math.subtract(m_tensor,10)
sub_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [-6, -5, -4]])>

In [73]:
another_sub_tensor = m_tensor - 10
another_sub_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [-6, -5, -4]])>

In [76]:
div_tensor = tf.math.divide(m_tensor, 10)
div_tensor

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.2, 1.3, 1.4],
       [0.4, 0.5, 0.6]])>

In [79]:
another_div_tensor = m_tensor/10
another_div_tensor

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.2, 1.3, 1.4],
       [0.4, 0.5, 0.6]])>

In [87]:
n_tensor = tf.constant([[12,13,14],
                        [2,3,4]])
print(m_tensor.numpy(), m_tensor.shape, m_tensor.ndim)
print(n_tensor.numpy(), n_tensor.shape, n_tensor.ndim)

[[12 13 14]
 [ 4  5  6]] (2, 3) 2
[[12 13 14]
 [ 2  3  4]] (2, 3) 2


In [88]:
tf.math.add(m_tensor, n_tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 26, 28],
       [ 6,  8, 10]])>

In [89]:
tf.math.subtract(m_tensor, n_tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [2, 2, 2]])>

In [91]:
tf.math.multiply(m_tensor, n_tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[144, 169, 196],
       [  8,  15,  24]])>

In [92]:
tf.math.divide(m_tensor, n_tensor)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.        , 1.        , 1.        ],
       [2.        , 1.66666667, 1.5       ]])>

### Matrix Multiplication

In [126]:
tensor_a = tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])
tensor_a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]])>

In [166]:
tensor_b = tf.constant([[3,5],
                        [6,7],
                       [1,8]])
tensor_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]])>

In [96]:
tensor_a.ndim, tensor_b.ndim

(2, 2)

In [165]:
print(tensor_a.shape)
print(tensor_b.shape)

(3, 3)
(3, 2)


In [142]:
tensor_c = tf.tensordot(tensor_a, tensor_b,1)
tensor_c

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [136]:
tensor_d = tf.matmul(tensor_a, tensor_b)
tensor_d

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [146]:
tensor_e = tf.constant([[1,2],
                        [3,4],
                       [5,6]])
tensor_e

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [149]:
tensor_f = tf.constant([[7,8],
                        [9,10],
                       [11,12]])
tensor_f

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [158]:
tensor_e.shape, tensor_f.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [168]:
tensor_g = tf.reshape(tensor_f, shape=(2,3))
tensor_g

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [169]:
tf.tensordot(tensor_e, tensor_g,1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

#### matrix multiplication using python

In [157]:
tensor_a @ tensor_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

### transposing tensors

In [174]:
tensor_e, tf.reshape(tensor_e, shape=(2,3)), tf.transpose(tensor_e)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)