# Practice what I learn from the beginning to current

## Declaring the package or library

In [4]:
import tensorflow as tf
print(tf.__version__)

2.15.0


## Using tf.constant

### Scalar

In [33]:
scalar = tf.constant(5)
print("information of scalar:",scalar)
print ("shape of scalar:",scalar.shape)
print("data type of scalar:",scalar.dtype)
print("scalar value is:",scalar.numpy())
print("no. of dimension of scalar:",scalar.ndim)

information of scalar: tf.Tensor(5, shape=(), dtype=int32)
shape of scalar: ()
data type of scalar: <dtype: 'int32'>
scalar value is: 5
no. of dimension of scalar: 0


### Vector

In [34]:
vector = tf.constant([5,2])
print("information of vector:",vector)
print("shape of vector:",vector.shape)
print("data type of vector",vector.dtype)
print("vector value:",vector.numpy())
print("no. of dimension of vector:",vector.ndim)

information of vector: tf.Tensor([5 2], shape=(2,), dtype=int32)
shape of vector: (2,)
data type of vector <dtype: 'int32'>
vector value: [5 2]
no. of dimension of vector: 1


### Matrix

In [43]:
matrix = tf.constant([[5,3,2],
                      [2,6,9],
                      [9,4,6]])
print("information of matrix:\n",matrix)
print("shape of matrix:",matrix.shape)
print("data type of matrix:", matrix.dtype)
print("matrix value:\n",matrix.numpy())
print("no of dimension of matrix:",matrix.ndim)

information of matrix:
 tf.Tensor(
[[5 3 2]
 [2 6 9]
 [9 4 6]], shape=(3, 3), dtype=int32)
shape of matrix: (3, 3)
data type of matrix: <dtype: 'int32'>
matrix value:
 [[5 3 2]
 [2 6 9]
 [9 4 6]]
no of dimension of matrix: 2


### Tensor

In [47]:
tensor = tf.constant([[[6,3,6],
                       [4,2,5],
                       [3,5,6]],
                      [[1,54,2],
                       [5,3,2],
                       [4,3,6]]])
print("tensor information:\n",tensor)
print("tensor shape:",tensor.shape)
print("tensor data type:",tensor.dtype)
print("tensor value:\n",tensor.numpy())
print("tensor no. of dimensions",tensor.ndim)

tensor information:
 tf.Tensor(
[[[ 6  3  6]
  [ 4  2  5]
  [ 3  5  6]]

 [[ 1 54  2]
  [ 5  3  2]
  [ 4  3  6]]], shape=(2, 3, 3), dtype=int32)
tensor shape: (2, 3, 3)
tensor data type: <dtype: 'int32'>
tensor value:
 [[[ 6  3  6]
  [ 4  2  5]
  [ 3  5  6]]

 [[ 1 54  2]
  [ 5  3  2]
  [ 4  3  6]]]
tensor no. of dimensions 3


## Using of tf.Variable

In [530]:
var_tensor = tf.Variable([[3,4],
                          [5,6]])
var_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

In [533]:
var_tensor.assign([[1,2],
                  [76,33]])
var_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 1,  2],
       [76, 33]])>

## Using of tf.random

### usisng of tf.random.generator.from_see()

In [527]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### using of tf.random.normal

In [180]:
rand_tensor = tf.random.normal([2,3,3])
rand_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-1.2268713 ,  0.2612501 , -0.46333015],
        [-1.4015867 ,  1.3283775 ,  1.0398799 ],
        [-1.0119172 , -0.45224237, -1.5239854 ]],

       [[ 1.0320581 , -0.38796726, -1.0805458 ],
        [ 0.45629093,  1.4238765 , -1.3993766 ],
        [-1.5570542 ,  0.06404073, -1.214125  ]]], dtype=float32)>

### using tf.random.set_seed()

In [336]:
tf.random.set_seed(4)
another_rand_tensor = tf.random.normal([2,3,3])
another_rand_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.07676513, -0.2082602 ,  1.9333363 ],
        [ 1.175166  ,  1.4444144 ,  1.3351023 ],
        [ 0.0987538 ,  0.47003892, -0.89593434]],

       [[ 0.8269468 , -0.3298544 , -1.6903992 ],
        [ 2.1704402 , -1.0355538 ,  1.1871556 ],
        [ 0.44113445, -0.7447429 ,  1.2710264 ]]], dtype=float32)>

In [492]:
anotherone_rand_tensor = tf.random.set_seed(2)
anotherone_rand_tensor = tf.random.normal([2,3,3],seed=5)
anotherone_rand_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.39120236, -1.1576606 ,  0.87334764],
        [-0.7303882 ,  0.07501176,  1.620321  ],
        [ 1.8835862 , -1.3954105 ,  0.8211904 ]],

       [[ 0.29821634,  0.5768454 ,  0.6407048 ],
        [ 1.6286273 ,  0.3706698 ,  1.439593  ],
        [-0.15120259,  1.0260885 ,  1.1177633 ]]], dtype=float32)>