# Testing what I learn

### for declaring tensorflow as tf
* displaying of tensorflow version

In [2]:
import tensorflow as tf
print(tf.__version__)


2.15.0


### using of tf.constant()
1. as scalar - **0** dimension
2. as vector - **1** dimension
3. as matrix - **2** dimensions
4. as tensor - **n** dimensions

* using of ndim (number of dimensions)

In [3]:
#as scalar
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [10]:
tensor.ndim

3

### using tf.Variable()

In [11]:
variable_tensor = tf.Variable([[1,2,3],[4,5,6]])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
variable_tensor.shape, tf.size(variable_tensor)

(TensorShape([2, 3]), <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [13]:
variable_tensor.assign([[10,11,12],
                       [13,14,15]])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 11, 12],
       [13, 14, 15]])>

In [14]:
variable_tensor.assign([
    [2,3,4],
    [5,6,7],
])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]])>

### using tf.shuffle()

In [15]:
shuffle_tensor = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
shuffle_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [16]:
tf.random.shuffle(shuffle_tensor)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])>

### using tf.random()

In [17]:
random_tensor = tf.random.normal([2,3,3,])
random_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 1.9516399 , -0.53109086,  1.1277083 ],
        [ 0.09506121, -1.9545355 , -0.9390517 ],
        [ 0.7460742 , -0.01543848,  0.2970789 ]],

       [[-0.3020748 ,  1.1377187 ,  0.1767173 ],
        [-0.9415953 , -0.18187168,  0.39892814],
        [ 1.3391489 , -0.12433875, -0.9370562 ]]], dtype=float32)>

In [18]:
tf.random.set_seed(3)
random_tensor = tf.random.normal([2,3,3])
random_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.8296372 , -1.8266271 ,  0.1251936 ],
        [ 1.1770082 , -1.1696676 , -0.0093245 ],
        [ 1.7336212 , -1.0343224 ,  0.13810681]],

       [[-0.91464186, -1.1291755 ,  1.8039238 ],
        [-0.2886803 , -0.8180008 ,  1.6706624 ],
        [ 0.59479725,  1.9857334 , -0.39366513]]], dtype=float32)>

In [19]:
zeros = tf.zeros([2,2,3,3])
zeros

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [20]:
ones = tf.ones([2,2,3,3])
ones

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

### Getting tensor informations

In [21]:
tensor_info = tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]],
        [
            [13,14,15,16],
            [17,18,19,20],
            [21,22,23,24]
        ]
    ]
])
tensor_info

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])>

In [22]:
print("Size of tensor: ",tf.size(tensor_info).numpy())
print("Shape of tensor: ",tensor_info.shape)
print("Get the value of X-Y element of the tensor: ",(tensor_info.numpy()))
print("Elements along 0 axis: ", tensor_info.shape[0])
print("Elements along last axis: ", tensor_info.shape[-1])
print("Number of dimensions of the tensor: ", tensor_info.ndim)
print("Data type of the tensor: ", tensor_info.dtype)

Size of tensor:  24
Shape of tensor:  (1, 2, 3, 4)
Get the value of X-Y element of the tensor:  [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]]
Elements along 0 axis:  1
Elements along last axis:  4
Number of dimensions of the tensor:  4
Data type of the tensor:  <dtype: 'int32'>


### basic manipulation of operation in tensorflow

In [24]:
x = tf.constant([[2,2],
                [3,4],
                [5,6]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 4],
       [5, 6]])>

#### addition

In [43]:
print(tf.add(x, 10).numpy(),"\n")
print(tf.math.add(x, 10).numpy(),"\n")
print((x+10).numpy(),"\n")
print("shape of tensor x: ",x.shape, ", data type: ",x.dtype, "# of dimension: ",x.ndim)

[[12 12]
 [13 14]
 [15 16]] 

[[12 12]
 [13 14]
 [15 16]] 

[[12 12]
 [13 14]
 [15 16]] 

shape of tensor x:  (3, 2) , data type:  <dtype: 'int32'> # of dimension:  2


#### subtraction

In [33]:
print(tf.subtract(x, 10),"\n")
print(tf.math.subtract(x, 10),"\n")
print(x-10)

tf.Tensor(
[[-8 -8]
 [-7 -6]
 [-5 -4]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[-8 -8]
 [-7 -6]
 [-5 -4]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[-8 -8]
 [-7 -6]
 [-5 -4]], shape=(3, 2), dtype=int32)


#### multiplication

In [44]:
print(tf.multiply(x, 10),"\n")
print(tf.math.multiply(x, 10),"\n")
print((x*10))

tf.Tensor(
[[20 20]
 [30 40]
 [50 60]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[20 20]
 [30 40]
 [50 60]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[20 20]
 [30 40]
 [50 60]], shape=(3, 2), dtype=int32)


#### division

In [45]:
print(tf.divide(x,10),"\n")
print(tf.math.divide(x,10),"\n")
print(x/10)

tf.Tensor(
[[0.2 0.2]
 [0.3 0.4]
 [0.5 0.6]], shape=(3, 2), dtype=float64) 

tf.Tensor(
[[0.2 0.2]
 [0.3 0.4]
 [0.5 0.6]], shape=(3, 2), dtype=float64) 

tf.Tensor(
[[0.2 0.2]
 [0.3 0.4]
 [0.5 0.6]], shape=(3, 2), dtype=float64)


### multiplication of one tensor to another tensor

In [47]:
y = tf.constant([[4,5,7],
                [2,6,2],
                [6,8,2]])
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 7],
       [2, 6, 2],
       [6, 8, 2]])>

In [48]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[4, 5, 7],
        [2, 6, 2],
        [6, 8, 2]])>)

In [58]:
print(tf.multiply(y,10))
print(tf.matmul(y,x))
print(tf.tensordot(y,x,1))
y@x

tf.Tensor(
[[40 50 70]
 [20 60 20]
 [60 80 20]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[58 70]
 [32 40]
 [46 56]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[58 70]
 [32 40]
 [46 56]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[58, 70],
       [32, 40],
       [46, 56]])>

#### reshape

In [59]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[4, 5, 7],
        [2, 6, 2],
        [6, 8, 2]])>)

In [73]:
reshape_x = tf.reshape(x,shape=(2,3))
reshape_x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 3],
       [4, 5, 6]])>

In [74]:
reshape_x.shape, y.shape

(TensorShape([2, 3]), TensorShape([3, 3]))

In [75]:
tf.matmul(reshape_x,y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 46, 24],
       [62, 98, 50]])>

#### transposition

In [71]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[4, 5, 7],
        [2, 6, 2],
        [6, 8, 2]])>)

In [79]:
transpose_x = tf.transpose(x)
print(x,"\n")
print(reshape_x,"\n")
print(transpose_x)

tf.Tensor(
[[2 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[2 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[2 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [90]:
print("reshape matmul: ")
print(tf.matmul(reshape_x,y).numpy())
print("vs.\n")
print("transpose matmul: ")
print(tf.matmul(transpose_x,y).numpy())

reshape matmul: 
[[30 46 24]
 [62 98 50]]
vs.

transpose matmul: 
[[44 68 30]
 [52 82 34]]


### changing the data type of a tensor

In [91]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 4],
       [5, 6]])>

In [95]:
tf.cast(x,tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [99]:
tf.dtypes.cast(x,tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>