# Testing what I learn

### for declaring tensorflow as tf
* displaying of tensorflow version

In [5]:
import tensorflow as tf
print(tf.__version__)

2.15.0


### using of tf.constant()
1. as scalar - **0** dimension
2. as vector - **1** dimension
3. as matrix - **2** dimensions
4. as tensor - **n** dimensions

* using of ndim (number of dimensions)

In [8]:
#as scalar
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [10]:
scalar.ndim

0

In [12]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [14]:
vector.ndim

1

In [16]:
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [17]:
matrix.ndim

2

In [18]:
tensor = tf.constant([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [19]:
tensor.ndim

3

### using tf.Variable()

In [25]:
variable_tensor = tf.Variable([[1,2,3],[4,5,6]])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [39]:
variable_tensor.shape, tf.size(variable_tensor)

(TensorShape([2, 3]), <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [35]:
variable_tensor.assign([[10,11,12],
                       [13,14,15]])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 11, 12],
       [13, 14, 15]])>

In [138]:
variable_tensor.assign([
    [2,3,4],
    [5,6,7],
])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]])>

### using tf.shuffle()

In [140]:
shuffle_tensor = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
shuffle_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [139]:
tf.random.shuffle(shuffle_tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

### using tf.random()

In [136]:
random_tensor = tf.random.normal([2,3,3,])
random_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 0.02758301,  1.0955776 ,  0.64639515],
        [-0.87001896, -0.76624453,  0.39096865],
        [ 0.5912294 , -2.3281837 , -1.6424481 ]],

       [[ 0.53366745,  0.252087  ,  1.2605014 ],
        [-0.25704494, -0.8996516 , -1.2905672 ],
        [ 1.5495535 ,  0.65709054, -0.91293406]]], dtype=float32)>

In [109]:
tf.random.set_seed(3)
random_tensor = tf.random.normal([2,3,3])
random_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.8296372 , -1.8266271 ,  0.1251936 ],
        [ 1.1770082 , -1.1696676 , -0.0093245 ],
        [ 1.7336212 , -1.0343224 ,  0.13810681]],

       [[-0.91464186, -1.1291755 ,  1.8039238 ],
        [-0.2886803 , -0.8180008 ,  1.6706624 ],
        [ 0.59479725,  1.9857334 , -0.39366513]]], dtype=float32)>

In [145]:
zeros = tf.zeros([2,2,3,3])
zeros

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [148]:
ones = tf.ones([2,2,3,3])
ones

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

### Getting tensor informations

In [203]:
tensor_info = tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]],
        [
            [13,14,15,16],
            [17,18,19,20],
            [21,22,23,24]
        ]
    ]
])
tensor_info

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])>

In [242]:
print("Size of tensor: ",tf.size(tensor_info).numpy())
print("Shape of tensor: ",tensor_info.shape)
print("Get the value of X-Y element of the tensor: ",(tensor_info.numpy()))
print("Elements along 0 axis: ", tensor_info.shape[0])
print("Elements along last axis: ", tensor_info.shape[-1])
print("Number of dimensions of the tensor: ", tensor_info.ndim)
print("Data type of the tensor: ", tensor_info.dtype)

Size of tensor:  24
Shape of tensor:  (1, 2, 3, 4)
Get the value of X-Y element of the tensor:  [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]]
Elements along 0 axis:  1
Elements along last axis:  4
Number of dimensions of the tensor:  4
Data type of the tensor:  <dtype: 'int32'>
