# Practice what I learn from the beginning to current

## Declaring the package or library

In [2]:
import tensorflow as tf
print(tf.__version__)


2.15.0


## Using tf.constant

### Scalar

In [3]:
scalar = tf.constant(5)
print("information of scalar:",scalar)
print ("shape of scalar:",scalar.shape)
print("data type of scalar:",scalar.dtype)
print("scalar value is:",scalar.numpy())
print("no. of dimension of scalar:",scalar.ndim)

information of scalar: tf.Tensor(5, shape=(), dtype=int32)
shape of scalar: ()
data type of scalar: <dtype: 'int32'>
scalar value is: 5
no. of dimension of scalar: 0


### Vector

In [4]:
vector = tf.constant([5,2])
print("information of vector:",vector)
print("shape of vector:",vector.shape)
print("data type of vector",vector.dtype)
print("vector value:",vector.numpy())
print("no. of dimension of vector:",vector.ndim)

information of vector: tf.Tensor([5 2], shape=(2,), dtype=int32)
shape of vector: (2,)
data type of vector <dtype: 'int32'>
vector value: [5 2]
no. of dimension of vector: 1


### Matrix

In [5]:
matrix = tf.constant([[5,3,2],
                      [2,6,9],
                      [9,4,6]])
print("information of matrix:\n",matrix)
print("shape of matrix:",matrix.shape)
print("data type of matrix:", matrix.dtype)
print("matrix value:\n",matrix.numpy())
print("no of dimension of matrix:",matrix.ndim)

information of matrix:
 tf.Tensor(
[[5 3 2]
 [2 6 9]
 [9 4 6]], shape=(3, 3), dtype=int32)
shape of matrix: (3, 3)
data type of matrix: <dtype: 'int32'>
matrix value:
 [[5 3 2]
 [2 6 9]
 [9 4 6]]
no of dimension of matrix: 2


### Tensor

In [6]:
tensor = tf.constant([[[6,3,6],
                       [4,2,5],
                       [3,5,6]],
                      [[1,54,2],
                       [5,3,2],
                       [4,3,6]]])
print("tensor information:\n",tensor)
print("tensor shape:",tensor.shape)
print("tensor data type:",tensor.dtype)
print("tensor value:\n",tensor.numpy())
print("tensor no. of dimensions",tensor.ndim)

tensor information:
 tf.Tensor(
[[[ 6  3  6]
  [ 4  2  5]
  [ 3  5  6]]

 [[ 1 54  2]
  [ 5  3  2]
  [ 4  3  6]]], shape=(2, 3, 3), dtype=int32)
tensor shape: (2, 3, 3)
tensor data type: <dtype: 'int32'>
tensor value:
 [[[ 6  3  6]
  [ 4  2  5]
  [ 3  5  6]]

 [[ 1 54  2]
  [ 5  3  2]
  [ 4  3  6]]]
tensor no. of dimensions 3


## Using of tf.Variable

In [7]:
var_tensor = tf.Variable([[3,4],
                          [5,6]])
var_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

In [8]:
var_tensor.assign([[1,2],
                  [76,33]])
var_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 1,  2],
       [76, 33]])>

## Using of tf.random

### using of tf.random.generator.from_see()

In [9]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### using of tf.random.normal

In [10]:
rand_tensor = tf.random.normal([2,3,3])
rand_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 0.6999161 ,  2.4721835 , -1.0455236 ],
        [-0.6702676 ,  1.74496   ,  1.3070139 ],
        [ 0.98416597,  0.31412575,  0.41763833]],

       [[-1.1392218 ,  0.37036958, -1.2095699 ],
        [-0.22863378,  1.5090904 ,  1.4623171 ],
        [ 0.3051169 ,  1.9701606 ,  0.5279357 ]]], dtype=float32)>

### using tf.random.set_seed()

In [11]:
tf.random.set_seed(4)
another_rand_tensor = tf.random.normal([2,3,3])
another_rand_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.07676513, -0.2082602 ,  1.9333363 ],
        [ 1.175166  ,  1.4444144 ,  1.3351023 ],
        [ 0.0987538 ,  0.47003892, -0.89593434]],

       [[ 0.8269468 , -0.3298544 , -1.6903992 ],
        [ 2.1704402 , -1.0355538 ,  1.1871556 ],
        [ 0.44113445, -0.7447429 ,  1.2710264 ]]], dtype=float32)>

In [19]:
anotherone_rand_tensor = tf.random.set_seed(2)
anotherone_rand_tensor = tf.random.normal([2,3,3],seed=5)
anotherone_rand_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.39120236, -1.1576606 ,  0.87334764],
        [-0.7303882 ,  0.07501176,  1.620321  ],
        [ 1.8835862 , -1.3954105 ,  0.8211904 ]],

       [[ 0.29821634,  0.5768454 ,  0.6407048 ],
        [ 1.6286273 ,  0.3706698 ,  1.439593  ],
        [-0.15120259,  1.0260885 ,  1.1177633 ]]], dtype=float32)>

### using tf.shuffle()

In [23]:
x = tf.constant([[2,3,4],
                 [1,2,5],
                 [5,2,6]])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [1, 2, 5],
       [5, 2, 6]])>

In [67]:
print(anotherone_rand_tensor,"\n")
print(tf.random.shuffle(anotherone_rand_tensor))

tf.Tensor(
[[[-0.39120236 -1.1576606   0.87334764]
  [-0.7303882   0.07501176  1.620321  ]
  [ 1.8835862  -1.3954105   0.8211904 ]]

 [[ 0.29821634  0.5768454   0.6407048 ]
  [ 1.6286273   0.3706698   1.439593  ]
  [-0.15120259  1.0260885   1.1177633 ]]], shape=(2, 3, 3), dtype=float32) 

tf.Tensor(
[[[ 0.29821634  0.5768454   0.6407048 ]
  [ 1.6286273   0.3706698   1.439593  ]
  [-0.15120259  1.0260885   1.1177633 ]]

 [[-0.39120236 -1.1576606   0.87334764]
  [-0.7303882   0.07501176  1.620321  ]
  [ 1.8835862  -1.3954105   0.8211904 ]]], shape=(2, 3, 3), dtype=float32)


### using tf.ones()

In [76]:
tensor_ones = tf.ones([2,3,3])
print("tensor_ones information:\n",tensor_ones)
print("tensor_ones shape:",tensor_ones.shape)
print("tensor_ones data type:",tensor.dtype)
print("tensor_ones value:\n",tensor_ones.numpy())
print("tensor_ones no. of dimensions:",tensor_ones.ndim)

tensor_ones information:
 tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)
tensor_ones shape: (2, 3, 3)
tensor_ones data type: <dtype: 'int32'>
tensor_ones value:
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
tensor_ones no. of dimensions: 3


### using tf.zeros()

In [78]:
tensor_zeros = tf.zeros([3,3,3])
print("tensor_zeros information:\n",tensor_zeros)
print("tensor_zeros shape:", tensor_zeros.shape)
print("tensor_zeros data type:", tensor_zeros.dtype)
print("tensor_zeros value:\n", tensor_zeros.numpy())
print("tensor_zeros no. of dimensions:", tensor_zeros.ndim)

tensor_zeros information:
 tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)
tensor_zeros shape: (3, 3, 3)
tensor_zeros data type: <dtype: 'float32'>
tensor_zeros value:
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
tensor_zeros no. of dimensions: 3


### using numpy array

In [88]:
import numpy as np
numpy_arr = np.arange(1,25,dtype=np.int32)
print("numpy array information:\n",numpy_arr)

numpy array information:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


### converting numpy to tensor

In [101]:
print("elements of a tensor should be: ",2*3*4)
tensor_A = tf.constant(numpy_arr,shape=([2,3,4]))
tensor_A

elements of a tensor should be:  24


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

## Using Aggregation in tensorflow

### using tf.abs()

In [103]:
abs_tensor = tf.abs(anotherone_rand_tensor)
abs_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0.39120236, 1.1576606 , 0.87334764],
        [0.7303882 , 0.07501176, 1.620321  ],
        [1.8835862 , 1.3954105 , 0.8211904 ]],

       [[0.29821634, 0.5768454 , 0.6407048 ],
        [1.6286273 , 0.3706698 , 1.439593  ],
        [0.15120259, 1.0260885 , 1.1177633 ]]], dtype=float32)>

### using reduce_min()

In [111]:
a = tf.constant([[4,5,2],
                 [6,7,1],
                 [3,9,8]])
a, tf.reduce_min(a),tf.reduce_max(a),tf.reduce_mean(a),tf.reduce_sum(a)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[4, 5, 2],
        [6, 7, 1],
        [3, 9, 8]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>)

In [231]:
np_rand = tf.constant(np.random.randint(0,100,size=50))
print("np_rand information:\n",np_rand)
print("finding the minimum:\t",tf.reduce_min(np_rand))
print("finding the maximum:\t",tf.reduce_max(np_rand))
print("finding the mean:\t",tf.reduce_mean(np_rand))
print("finding the sum:\t",tf.reduce_sum(np_rand))
print("finding the variance:\t",tf.math.reduce_variance(tf.cast(np_rand,tf.float32)))
print("finding the std dev:\t",tf.math.reduce_std(tf.cast(np_rand,tf.float32)))
print("finding the positional maximum index:\n",tf.math.argmax(np_rand))
print("finding the positional minimum index:\n",tf.math.argmin(np_rand))

np_rand information:
 tf.Tensor(
[88 56 88  4 86  0 57 46 34 36 18 41 33 39 23 18 86  3 97 48 51 24 21 46
 65 98  3 45 88 28 99  4 43 55 65 79 18 78 50 70 96  9  5 46 85 13 17 88
 46 22], shape=(50,), dtype=int32)
finding the minimum:	 tf.Tensor(0, shape=(), dtype=int32)
finding the maximum:	 tf.Tensor(99, shape=(), dtype=int32)
finding the mean:	 tf.Tensor(47, shape=(), dtype=int32)
finding the sum:	 tf.Tensor(2358, shape=(), dtype=int32)
finding the variance:	 tf.Tensor(915.81445, shape=(), dtype=float32)
finding the std dev:	 tf.Tensor(30.262426, shape=(), dtype=float32)
finding the positional maximum index:
 tf.Tensor(30, shape=(), dtype=int64)
finding the positional minimum index:
 tf.Tensor(5, shape=(), dtype=int64)


In [160]:
5*1*2*5

50

In [164]:
tf_rand = tf.constant(np_rand,shape=[2,5,5])
tf_rand

<tf.Tensor: shape=(2, 5, 5), dtype=int32, numpy=
array([[[95,  0, 72, 75, 13],
        [66, 45, 24, 97, 22],
        [ 6, 57, 38, 21, 50],
        [ 1, 36, 52, 54, 60],
        [89, 97,  7, 63, 13]],

       [[90, 97, 73, 40, 32],
        [32, 10, 10, 26, 33],
        [66, 47, 14, 69, 88],
        [78, 50, 52, 56, 81],
        [76, 45, 90, 57, 67]]])>

In [235]:
tf.random.set_seed(42)
f = tf.random.uniform([50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [243]:
tf.math.argmax(f),f[tf.argmax(f)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [240]:
tf.math.argmin(f),f[tf.argmin(f)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor(removing all single dimensions)

In [268]:
tf.random.set_seed(42)
s_tensor = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
s_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [274]:
print(s_tensor.shape)
print(tf.squeeze(s_tensor).shape)

(1, 1, 1, 1, 50)
(50,)


In [277]:
print(s_tensor.numpy(),"\n")
print(tf.squeeze(s_tensor).numpy())

[[[[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
     0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
     0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
     0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
     0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
     0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
     0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
     0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
     0.7381023  0.32054043]]]]] 

[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.

## Using one-hot encode

In [290]:
index = [0 ,1 ,-1 ,3] # could be red, green, blue, purple
depth = 4
onehot_tensor = tf.one_hot(index,depth,on_value=5.0,off_value=0.0)
onehot_tensor, onehot_tensor.shape, onehot_tensor.ndim, tf.size(onehot_tensor).numpy(), onehot_tensor.dtype

(<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[5., 0., 0., 0.],
        [0., 5., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 5.]], dtype=float32)>,
 TensorShape([4, 4]),
 2,
 16,
 tf.float32)

In [334]:
tf.config.list_physical_devices("GPU")

[]